version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: always
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: uranai_db
      POSTGRES_USER: uranai_user
      POSTGRES_PASSWORD: uranai_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json  # ✅ サーバー設定をマウント
    env_file:  # ✅ `.env` ファイルを読み込む
      - .env
    ports:
      - "5050:80"  # ホストのポート5050でアクセス
    depends_on:
      - db

volumes:
  postgres_data:
