# Generated by Django 5.1.6 on 2025-02-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uranai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tarot_images/')),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TarotReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_combination', models.CharField(max_length=50, unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
