from uranai.models import TarotCard

# タロットカードの一覧（78枚）
tarot_cards = [
    {"card_no": 1, "name": "The Fool", "meaning": "新しい始まり"},
    {"card_no": 2, "name": "The Magician", "meaning": "創造力と行動力"},
    {"card_no": 3, "name": "The High Priestess", "meaning": "直感と神秘"},
    {"card_no": 4, "name": "The Empress", "meaning": "豊かさと母性"},
    {"card_no": 5, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 6, "name": "The Hierophant", "meaning": "伝統と信仰"},
    {"card_no": 7, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 8, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 9, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 10, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 11, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 12, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 13, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 14, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 15, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 16, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 17, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 18, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 19, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 20, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 21, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 22, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 23, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 24, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 25, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 26, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 27, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 28, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 29, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 30, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 31, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 32, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 33, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 34, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 35, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 36, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 37, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 38, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 39, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 40, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 41, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 42, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 43, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 44, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 45, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 46, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 47, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 48, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 49, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 50, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 51, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 52, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 53, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 54, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 55, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 56, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 57, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 58, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 59, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 60, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 61, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 62, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 63, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 64, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 65, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 66, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 67, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 68, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 69, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 70, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 71, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 72, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 73, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 74, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 75, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 76, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 77, "name": "The Emperor", "meaning": "支配と安定"},
    {"card_no": 78, "name": "The Emperor", "meaning": "支配と安定"}
]

# データ登録（`card_no` を主キーにして登録）
for card in tarot_cards:
    TarotCard.objects.update_or_create(
        card_no=card["card_no"],
        defaults={"name": card["name"], "meaning": card["meaning"]}
    )

print("✅ タロットカードの登録が完了しました！")
